pbkhrv/rtl_433-hass-addons

rtl_433/Dockerfile

The upstream `rtl_433` docs currently link to https://github.com/hertzg/rtl_433_docker as the recommended Docker images. Taking a look at it's [Dockerfile](https://github.com/hertzg/rtl_433_docker/blob/master/images/alpine/build-context/Dockerfile), it's got some nice improvements over what currently ships in this repo:
1. It uses a build container instead of inlining all of the steps into a single `RUN` step, making it easier to read.
2. It uses `librtlsdr-dev` from Alpine instead of compiling it from source.
3. `make -j4` improves compilation time a small amount.
4. It doesn't look like you need the `LD_LIBRARY_PATH` anymore (probably by installing the library via apk). I have run this Dockerfile on both amd64 and aarch64 without issues.
There's a small image size reduction by around …

Mirror Dockerfile from hertzg/rtl_433_docker

---

rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/build.json

Home Assistant builds base images with python that are recommended for addons, as it makes it much more likely there will be shared layers between multiple addons needing python: https://github.com/home-assistant/docker-base#python-images
While the final built image is larger than the current one, we can see that the actual steps far less space:
```
$ docker history 1b2e70f88a27
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
1b2e70f88a27   3 minutes ago   CMD ["/run.sh"]                                 0B        buildkit.dockerfile.v0
<missing>      3 minutes ago   RUN /bin/ash -o pipefail -c chmod a+x /run.s…   642B      buildkit.dockerfile.v0
<missing>      3 minutes ago   COPY run.sh / # buildkit                        642B …
```

Use hassio python base image

---

rtl_433/README.md
rtl_433/config.json
rtl_433/run.sh

Todo:
I'm considering updating the auto-discovery addon to be a separate PR. My thinking is that we get that working first, and then follow up with upstream to see if one or two addons is preferred.

Support multiple templated configuration files for multiple radios

---

rtl_433/config.json

I know there's some open issues about build failures, and they may not be fixed in main. However, updating the version will at least ensure everyone testing is on the same commit, at least in the short term.

Update version for new upstream rtl_433 release (#33)

---

rtl_433/Dockerfile

Fixes #41 as suggested by @deviantintegral. To recreate the issue, version v1.2 needs to be installed and then updated to v1.3.

Prevent using old cached rtl_433 repository during installation or update

---

.github/pull_request_template.md

To use the template I'm filing here:
This PR:
1. Asks contributors to set the default branch for merging (we can always change this ourselves if needed).
2. Reminds contributors that the HASS bridge script is actually maintained upstream.
Since changing the default branch affects users, the best way I can think of to handle it is with documentation.
1. Unfortunately, this will need to be merged to the main branch to actually test. I'm going to do that since this is not going to affect users, and hotfix any fixups needed with the issue number directly to main.

Add an initial pull request template #47

---

.github/workflows/builder.yml

This PR replaces https://github.com/pbkhrv/rtl_433-hass-addons/pull/53 and is basically identical. The most significant difference is that we don't yet put in `image` lines to `config.json`. In other words, we'll be creating images, making sure they build correctly, and pushing them to GitHub, but they won't be consumed unless someone manually pulls the images.
Images are built for:
- Pull requests (forks have to be approved by maintainers to run the job)
- main
- next
We could have pushed to Docker Hub, but that would require more work without an obvious benefit.
1. See the PR build.
2. Test pulling the pushed images.
3. Test manually running the images by pulling them with Supervisor's CLI, retagging them locally, and starting the addon.
4. Test by reinstalling the addon with a local …

Add workflow to build images for all architectures

---

.github/workflows/builder.yml

This ensures that if the repository is forked, jobs push images to the forked repository instead of trying (and failing) to push the images here. This also fixes pushing to the organization instead of the repository (I misread the docs on how that works).
1. I tested this at https://github.com/deviantintegral/rtl_433-hass-addons/pull/1 so as long as builds here pass we should be good.

Use variables for registry and repository

---

.github/workflows/builder.yml

I misunderstood how secrets in forks works for actions. While they get a token, that token may not have permission to push. I had thought I could approve the build, which is true, but it still doesn't give forks the secrets needed to push.
This PR changes CI to only _build_ and not push from forks. As well, it switches to using matrix jobs, as even after a job is complete all of the logs are jumbled together.
I considered using `pull_request_target` to reduce secrets restrictions, but I think the risks outweigh the gains. If a contributor really needs images pushed to the registry, we can open a new PR from a branch or the contributor can open a PR to their own fork to trigger it.
1. I'm opening this PR from my own fork. It should build, but not push.
2. I will then open the same code as …

Fix pushing images from forks

---

rtl_433_mqtt_autodiscovery/1665.diff
rtl_433_mqtt_autodiscovery/Dockerfile

Fixes the startup error as detailed at https://github.com/merbanan/rtl_433/pull/1665#issuecomment-1034168299

Roll back protocol and path changes in 1665 patch

---

rtl_433_mqtt_autodiscovery/README.md

This updates the documentation as a workaround for those who live in busy areas.
https://community.home-assistant.io/t/home-assistant-add-on-rtl-433-with-mqtt-auto-discovery/260665/159?u=deviantintegral
It would be neat to have a discovery UI and a way to automatically remove old devices, but this will improve most user's experience for now.

Recommend running the discovery addon as needed

---

.github/workflows/builder.yml
.github/workflows/release.yml
rtl_433/CHANGELOG.md
rtl_433_mqtt_autodiscovery/CHANGELOG.md

Adds missing aarch64 builds as reported at https://community.home-assistant.io/t/home-assistant-add-on-rtl-433-with-mqtt-auto-discovery/260665/171?u=deviantintegral
1. Make sure aarch64 builds in the action logs

Add aarch64 builds

---

README.md
rtl_433/CHANGELOG.md
rtl_433/Dockerfile
rtl_433/config.json
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/config.json

Update upstream rtl_433

---

rtl_433/Dockerfile
rtl_433/run.sh

Fixes #85 .
There are other ways to force unbuffered output, but this is by far the clearest to future maintainers.
1. Enable `output kv`
2. Run the addon or docker container.
3. There shouldn't be any obvious lag log output.

Fix output lag due to sed buffering #85

---

rtl_433/run.sh

Fixes #81 .
We could use sed for this as well, but that seems more complicated. There's no harm in an extra blank line for the case where the file contains it like normal.
1. Remove the trailing newline from a configuration file: https://stackoverflow.com/questions/1050640/how-to-stop-vim-from-adding-a-newline-at-end-of-file
2. Run the addon with the config file.
3. It should work instead of erroring out parsing the configuration.

Ensure template has an EOL character when rendering #81

---

rtl_433/Dockerfile
rtl_433_mqtt_autodiscovery/Dockerfile

We'd like the fix for rain meters mentioned at https://github.com/pbkhrv/rtl_433-hass-addons/issues/117.
We could never upgrade and be sad.
1. Builds complete.
2. Pull the `#-merge` tag for this PR and overwrite the local tag, and restart.

Upgrade rtl 433 to the latest master #117

---

rtl_433/README.md

From what I've read, it looks like `newmodel` is the default behavior now, and this is no longer necessary to include. Here's where I saw that message: https://github.com/merbanan/rtl_433/pull/1546#issuecomment-720301219

docs(readme): rm newmodel as it is default

---

rtl_433/CHANGELOG.md
rtl_433_mqtt_autodiscovery/2102.diff
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile

This pulls in https://github.com/merbanan/rtl_433/pull/2102 based on feedback from upstream as well as adding support for Honeywell Doorbell secret knocks.
1. Pull `120-merge` from GCR when built and override the tag locally.
2. Verify that device discovery works.

Update patch for Update mqtt hass to include triggers #2102

---

.github/workflows/release.yml
rtl_433-next/README.md
rtl_433/CHANGELOG.md
rtl_433/run.sh
rtl_433_mqtt_autodiscovery/CHANGELOG.md

rtl_433 uses the hostname when calculating default topics. When switching between the normal and next versions, the hostname changes. That makes it difficult to switch back and forth since all of the devices will be in a different tree.
This PR adds an example and updates the README of the next addon.
I thought about simply hardcoding the topic always, but I think that adds an extra layer of confusion to the configuration that most users won't benefit from.
1.  Pull this build down, or build locally.
2. Add or uncomment the output line added in this PR in the configuration file.
3. Stop the regular addon, and install the next addon.
4. Messages should be published to the same existing topics.

Add example for preserving topic structure between versions

---

rtl_433/run.sh

This is what HA expects to receive otherwise it would fail with:
ValueError: Invalid datetime: sensor.bresser_5_in_1_utc provides
state '2022-12-31 05:33:33', which is missing timezone information
See: https://github.com/merbanan/rtl_433/issues/2293

run.sh: Use ISO timestamp with timezone and usec precision

---

rtl_433/CHANGELOG.md
rtl_433/config.json
rtl_433_mqtt_autodiscovery/config.json

Prepare for 0.4.0 / 0.6.0 release

---

rtl_433_mqtt_autodiscovery/README.md

Include architecture name for Raspberry Pi
1. First...
2. Then...
3. You should see... (screenshots or console text are helpful)

[docs] Include architecture name for Raspberry Pi

---

rtl_433_mqtt_autodiscovery/run.sh

Happens with default Docker config. Fixes #141.
1. First...
2. Then...
3. You should see... (screenshots or console text are helpful)

Fix port number is missing sometimes

---

rtl_433/CHANGELOG.md
rtl_433/run.sh

rtl433 expects numbers instead of true/false for retain flag. Don't know if this is the proper way to fix it, but it seems to work for me.

Fix wrong retain value when setting in mqtt connection string

---

rtl_433-next/build.json
rtl_433/Dockerfile
rtl_433_mqtt_autodiscovery-next/build.json
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/build.json
rtl_433_mqtt_hass.py

i386 nightly builds started failing 5 days ago. When I test locally on an amd64 machine, it builds fine. Yet, when I cross-compile from my ARM Mac it segfaults (in a different spot). I'd be surprised if that was related since my Mac goes through qemu to emulate i386, while there shouldn't be any emulation for i386 in GitHub actions.
So, let's try updating to the latest base images and see if that works. If not, I may disable the i386 builds as I imagine they aren't used much.
1. All builds pass.

Upgrade to the latest base images

---

rtl_433/CHANGELOG.md
rtl_433/Dockerfile
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile

A new release was made last week. There are some breaking changes but nothing that should affect the addon itself.
https://github.com/merbanan/rtl_433/releases/tag/23.11
1. Builds pass
2. `next` should already contain these changes
3. Once builds are complete, it is possible to download and manually overwrite the docker tag to force the stable install of the addon to use the newer version, even before it's released.

Update stable release of rtl_433

---

rtl_433_mqtt_autodiscovery-next/config.json
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/config.json

Resolves https://github.com/pbkhrv/rtl_433-hass-addons/issues/88
The README has documented not running autodiscovery all the time to prevent adding additional low-quality or TPMS sensors, so this just makes that step a bit easier.

Default mqtt_retain to true #88

---

rtl_433/CHANGELOG.md
rtl_433/config.json
rtl_433/run.sh
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/config.json

paho-mqtt released a new 2.x version last week, and we weren't pinning or specifying a specific version in the docker scripts.
Thanks to the report at https://github.com/fl4p/batmon-ha/issues/197 for confirming this.
I also snuck in some basic help message improvements for when the mqtt addon itself isn't available.
I'll file an upstream issue since this will break the out-of-the-box experience for the rtl_433 project too.
1. Pull `ghcr.io/pbkhrv/rtl_433-hass-addons-rtl_433_mqtt_autodiscovery-next-{arch}:180-merge` once builds are done.
2. Tag it locally as next or the 0.8.0 release to overwrite it locally.
3. Addon should start.

Downgrade paho-mqtt to 1.x

---

rtl_433-next/build.json
rtl_433/Dockerfile
rtl_433_mqtt_autodiscovery-next/build.json
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/build.json

Fixes #181
Adds support for RTL-SDR Blog V4 Dongle by upgrading base image, which includes an up to date version (2.0.1) of librtlsdr.
It would have been possible to fix this more narrowly by upgrading the base image only in rtl_433, or even by just upgrading librtlsdr. However, the base image would need to be upgraded eventually in any case.
Applied changes locally by copying updated version of addon to my Home Assistant Green running latest OS via Samba, with image field deleted from config.json to prevent use of pre-built Docker image.

Update base Home Assistant Alpine image to 3.19

---

rtl_433-next/build.json
rtl_433/CHANGELOG.md
rtl_433/Dockerfile
rtl_433/config.json
rtl_433_mqtt_autodiscovery-next/build.json
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/build.json
rtl_433_mqtt_autodiscovery/config.json

This updates the stable versions to include #181 .

Prepare release

---

rtl_433/Dockerfile

Include openssl-dev in Dockerfile, which will automatically include support into the built rtl_433 for `mqtts` targets.
n/a
* See #204 - witnessed error messages and inability to connect to mqtt broker.
* Installed local version of addon with `openssl-dev` added to the Dockerfile, confirmed ability to connect to `mqtts` (SSL) broker, no more error message in logs, and messages successfully going to broker.

Add support for openssl

---

rtl_433-next/build.json
rtl_433/CHANGELOG.md
rtl_433/Dockerfile
rtl_433/build.json
rtl_433_mqtt_autodiscovery-next/build.json
rtl_433_mqtt_autodiscovery/CHANGELOG.md
rtl_433_mqtt_autodiscovery/Dockerfile
rtl_433_mqtt_autodiscovery/build.json

Updates our base images from Alpine 3.19 to 3.21.
1. Images build!

Upgrade base images to Alpine 3.21
